name: Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "praveen10942@gmail.com"
          git config --global user.name "praveen10942"
          git remote add hf https://praveen10942:$HF_TOKEN@huggingface.co/spaces/praveen10942/banana-disease-detector || true
          git push hf main --force
